---
services:
  bind9:
    build:
      context: .
      dockerfile: Dockerfile
    configs:
      - source: named_conf
        target: /etc/bind/named.conf
        uid: "0"
        gid: "101"
        # trunk-ignore(yamllint/octal-values)
        mode: 0440
      - source: named_local_conf
        target: /etc/bind/named.local.conf
        uid: "0"
        gid: "101"
        # trunk-ignore(yamllint/octal-values)
        mode: 0440
    secrets:
      - axfr_conf
    volumes:
      - zones:/var/bind:rw
    network_mode: host

    depends_on:
      zones:
        condition: service_completed_successfully

  zones:
    image: busybox:1.36
    volumes:
      - ./config/zones:/zones:ro
      - zones:/var/bind:rw
    command: cp -ra /zones/. /var/bind/pri

configs:
  named_conf:
    file: config/named.conf
  named_local_conf:
    file: config/named.local.conf

secrets:
  axfr_conf:
    file: secrets/axfr.conf

volumes:
  zones: {}
